### PR TITLE
better performance using array of listeners

### PR DESCRIPTION
**Pull request by ahdinosaur**
since [`push-stream`](https://github.com/ahdinosaur/push-stream) (of which the core was more or less copied from [`geval`](https://github.com/Raynos/geval)) did well on @Hypercubed's [observable benchmark](https://github.com/Hypercubed/EventsSpeedTests), i thought it might be worth a try to re-write `pull-notify` using the same pattern.

changes:
- how to keep track of listeners
  - before: an object where keys are incrementing integers
  - after: an array
- how to notify listeners
  - before: iterate through keys with `for in` loop
  - after: iterate through indexes with `for` loop
- how to add listener
  - before: generate new key and set on object
  - after: push to array
- how to remove listener
  - before: delete the key from object
  - after: find index of listener with `indexOf` and remove with `splice`

benchmark [before](https://github.com/Hypercubed/EventsSpeedTests/blob/master/results/node-v6.2.tap.md) and [after](https://gist.github.com/ahdinosaur/6e72863d851516af3de1610217ce2766)

also updated code to standard style, per https://github.com/pull-stream/pull-stream/issues/52.

/cc @dominictarr

### CODE REVIEW

**Comment by ahdinosaur** [comment]
i also think https://github.com/pull-stream/pull-notify/commit/c10766173242ca85ffe204a0607a8f4b36081fcb is hurting performance, but since that would be a breaking change i'll wait til after this.

**Comment by dominictarr** [comment]
another thing you can do is have a fallback that skips the iteration until there is more than one listener. that will improve quite a bit I think.

**Comment by Hypercubed** [comment]
Yes, the fall back helps a lot.  xstream is an example.  That is also why I went with linked lists in MiniSignals.

**Comment by ahdinosaur** [comment]
hmm interesting, well i changed how `.end` iterates and got better results: https://github.com/pull-stream/pull-notify/pull/2, where `pull-notify` with a single listener now matches `pull-pushable` directly..

**Comment by ahdinosaur** [comment]
ignore previous comment about better results, apparently the original benches i posted above were just the old ones. :dizzy_face:

now [fixed](https://gist.github.com/ahdinosaur/6e72863d851516af3de1610217ce2766), with this change `pull-notify` is looking a much better than before. :tada:

**Pull request merged**
